#pragma once

#include <cstdint>
#include <string>
#include "aster/tsc_clock.hpp"

namespace aster {

using OrderId    = uint64_t;
using Price      = int64_t;          // fixed‑point, e.g. 1e-8 scaling
using Quantity   = uint64_t;
using Symbol     = std::string;
using Timestamp  = uint64_t;         // TSC ticks (converted to ns when needed)

enum class Side : uint8_t { Buy, Sell };
enum class OrderType : uint8_t { Limit, Market };

enum class EventType : uint8_t {
    AddOrder,
    OrderCancel,
    OrderModify,
    OrderReduce,        // partial fill (reduce quantity without losing time priority)
    Trade               // not used for event stream; trade events are generated by the engine
};

struct OrderEvent {
    Timestamp   timestamp;
    uint64_t    seq_no;
    OrderId     order_id;
    Symbol      symbol;
    Side        side;
    OrderType   type;
    Price       price;
    Quantity    quantity;
    EventType   event_type;
};

struct TradeEvent {
    Timestamp   timestamp;
    OrderId     resting_id;
    OrderId     aggressor_id;
    Symbol      symbol;
    Price       price;
    Quantity    quantity;
    Side        aggressor_side;
};

struct BookUpdate {
    Timestamp   timestamp;
    Symbol      symbol;
    Side        side;
    Price       price;
    Quantity    total_quantity;
    uint32_t    order_count;
};

} // namespace aster
